### ISSUE TITLE
[question] linux-x64 Version

### ISSUE THREAD

**Issue by HenkerX64** [Citrinate/BoosterManager#1]
Hello,
do you plan linux version or it stays ASF-generic version?

It is interesting to use this plugin for docker setup.

Thanks

**Comment by Citrinate** [comment]
I've done some testing and made some changes that should improve compatibility with linux-x64.  If you'd like to test here's the latest build: [BoosterManager.zip](https://github.com/Citrinate/BoosterManager/files/10096699/BoosterManager.zip)

I don't plan on ever officially supporting anything other than ASF-generic, but if things do break for linux-x64 I'd be willing to look into it.

**Comment by HenkerX64** [comment]
Thanks!!! It works perfect
