### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Semidvista** [Citrinate/BoosterManager#10]
2023-12-23 16:16:42|ArchiSteamFarm-20204|ERROR|0.HustleHardy|GetItemsFromStacks() Not enough available quantity to complete trade, need 3, but only 0 are available
2023-12-23 16:16:42|ArchiSteamFarm-20204|INFO|0.HustleHardy|SendMultipleItemsWithAmounts() Not enough of 753::6::xxxxxxxxxxx to send!
2023-12-23 16:16:42|ArchiSteamFarm-20204|ERROR|0.HustleHardy|BatchSendMultipleItemsWithAmounts() Failed to send items to 2.1
![9lZ-nd0Se-o](https://github.com/Citrinate/BoosterManager/assets/130897671/14b4fd39-0e5c-4127-b9f8-d7c83c216159)

**Comment by Citrinate** [comment]
I don't see a bug here, it looks more like you're just using a command incorrectly.  To know for certain I'd need to know what you were trying to do and what you expected to happen.

It looks like you're trying to send 3 of some item from one account to another account.  The format you're using to select which item to send is `AppID::ContextID::ClassID`.  You used `753::6::xxxxxxxxxxx` which would be an item under the "Community" tab in your "Steam" inventory.  Not sure why you edited the `ClassID` out as it's not supposed to contain sensitive information.  I can see what the number was in your original post, and it looks too large to be a `ClassID`.  It looks more like an `AssetID`, which is an invalid input for this command and so it makes sense that the plugin wouldn't find anything.

**Comment by influence412** [comment]
> I don't see a bug here, it looks more like you're just using a command incorrectly. To know for certain I'd need to know what you were trying to do and what you expected to happen.
> 
> It looks like you're trying to send 3 of some item from one account to another account. The format you're using to select which item to send is `AppID::ContextID::ClassID`. You used `753::6::xxxxxxxxxxx` which would be an item under the "Community" tab in your "Steam" inventory. Not sure why you edited the `ClassID` out as it's not supposed to contain sensitive information. I can see what the number was in your original post, and it looks too large to be a `ClassID`. It looks more like an `AssetID`, which is an invalid input for this command and so it makes sense that the plugin wouldn't find anything.

this is ClassID, right? 
![image](https://github.com/Citrinate/BoosterManager/assets/154758173/4aabf04b-991b-4ec5-87a7-d155776fb977)

**Comment by influence412** [comment]
> I don't see a bug here, it looks more like you're just using a command incorrectly. To know for certain I'd need to know what you were trying to do and what you expected to happen.
> 
> It looks like you're trying to send 3 of some item from one account to another account. The format you're using to select which item to send is `AppID::ContextID::ClassID`. You used `753::6::xxxxxxxxxxx` which would be an item under the "Community" tab in your "Steam" inventory. Not sure why you edited the `ClassID` out as it's not supposed to contain sensitive information. I can see what the number was in your original post, and it looks too large to be a `ClassID`. It looks more like an `AssetID`, which is an invalid input for this command and so it makes sense that the plugin wouldn't find anything.

The plugin also does not work with hash name

**Comment by Citrinate** [comment]
> The plugin also does not work with hash name

Can you give an example of the command you're trying to use?

> this is ClassID, right?

That's an AssetID.  You can find the ClassID by searching for `var g_rgAssets` in the source code for an item's market page.  [Sack of Gems](https://steamcommunity.com/market/listings/753/753-Sack%20of%20Gems) for example contains this text where `appid`, `contextid`, and `classid` are all defined:

> var g_rgAssets = {"753":{"6":{"28448181377":{"currency":0,<ins>**"appid":753,"contextid":"6"**</ins>,"id":"28448181377",<ins>**"classid":"667933237"**</ins>,"insta...

**Comment by influence412** [comment]
I

> > The plugin also does not work with hash name
> 
> Can you give an example of the command you're trying to use?
> 
> > this is ClassID, right?
> 
> That's an AssetID. You can find the ClassID by searching for `var g_rgAssets` in the source code for an item's market page. [Sack of Gems](https://steamcommunity.com/market/listings/753/753-Sack%20of%20Gems) for example contains this text where `appid`, `contextid`, and `classid` are all defined:
> 
> > var g_rgAssets = {"753":{"6":{"28448181377":{"currency":0,**"appid":753,"contextid":"6"**,"id":"28448181377",**"classid":"667933237"**,"insta...

It works! Thank you<3

**Comment by influence412** [comment]
> > The plugin also does not work with hash name
> 
> Can you give an example of the command you're trying to use?
> 
> > this is ClassID, right?
> 
> That's an AssetID. You can find the ClassID by searching for `var g_rgAssets` in the source code for an item's market page. [Sack of Gems](https://steamcommunity.com/market/listings/753/753-Sack%20of%20Gems) for example contains this text where `appid`, `contextid`, and `classid` are all defined:
> 
> > var g_rgAssets = {"753":{"6":{"28448181377":{"currency":0,**"appid":753,"contextid":"6"**,"id":"28448181377",**"classid":"667933237"**,"insta...

Semidvista is my friend, you can close issue
