### ISSUE TITLE
Error when creating boosters

### ISSUE THREAD

**Issue by AirPirat** [Citrinate/BoosterManager#16]
After ASF was updated, I get an error when trying to create boosters, I also updated BoosterManager, I have to use old versions of ASF and BoosterManager
![image](https://github.com/Citrinate/BoosterManager/assets/114617803/7e2e62ab-03ae-431d-8b96-82baed88a544)

**Comment by Citrinate** [comment]
This is usually a temporary Steam issue.  The plugin will retry every minute until it succeeds.  This is only an issue if the error persists for a long period of time.

**Comment by AirPirat** [comment]
There was no problem today
