### ISSUE TITLE
Add support for crafting multiple identical booster packs

### ISSUE THREAD

**Issue by Nuklon** [Citrinate/BoosterManager#17]
Right now you need to run a daily command to craft more booster packs of the app ids you want.
It'd be useful to add another command to booster:
```
booster [Bots] <AppIDs> <Number>
```
If ```<Number>``` is omitted: 1
If ```<Number>``` is passed in, such as 2, then it schedules one now, another one tomorrow, etc.

**Comment by Citrinate** [comment]
There's a `GamesToBooster` config setting that lets you craft the same boosters endlessly.  Is that not sufficient for this type of thing?  Personally I'm not sure why I would ever want to, for example, craft 3 of the same booster, but not 4.

**Comment by Nuklon** [comment]
> There's a `GamesToBooster` config setting that lets you craft the same boosters endlessly. Is that not sufficient for this type of thing? Personally I'm not sure why I would ever want to, for example, schedule 3 of the same booster, but not 4.

Not really, I'll forget about it and then I'll get too many crafted. If I want to make a badge complete I would like to be able to generate X booster packs.

**Comment by Citrinate** [comment]
Alright, I think this makes sense.  Dunno when I'll get around to implementing it though.

**Comment by Citrinate** [comment]
I'll publish a release with this feature probably in the next few days.  If you'd like to test it early here's the latest build: [BoosterManager V2.10.0](https://github.com/Citrinate/BoosterManager/actions/runs/9147241977/artifacts/1516996525).  There's no special command syntax for doing this, the `booster` command just allows for duplicates now.  To queue up 2 of the same booster for example you can do either of:

`booster botA 440,440`

or 

`booster botA 440`
`booster botA 440`

The plugin now also saves and restores any unfinished `booster` commands when ASF is restarted, to accommodate for the possibility that these commands may now take much more than 24 hours to complete.

**Comment by woctezuma** [comment]
Nice! 😄

**Comment by Citrinate** [comment]
There will also be a new command: 

`booster^ [Bots] <AppIDs> <Amounts>`

Documented currently as:

>Adds `AppIDs` to some or all of given bot's booster queues, selected in a way to minimize the time it takes to craft a total `Amount` of boosters.  The `Amounts` specified may be a single amount for all `AppIDs`, or multiple amounts for each `AppID` respectively.

So if you want to queue up 2 of a booster for a single bot you can use: 

`booster^ botA 440 2`

And if you want to craft 2 boosters in the least time possible, you can pass this command multiple bots and let the plugin decide which bots do the crafting:

`booster^ botA,botB,botC 440 2`

**Comment by Nuklon** [comment]
Thanks @Citrinate, I've just added some boosters to queue with `booster^`, the first ones are crafted 🚀
