### ISSUE TITLE
transfergems enhancement

### ISSUE THREAD

**Issue by Nuklon** [Citrinate/BoosterManager#22]
> transfergems xx yy
< <yy> Successfully sent nothing!

Perhaps this message can be rewritten and changed to include a message that you need to specify the number of gems.

**Comment by Citrinate** [comment]
Technically the amount isn't missing there.  The first `[Bot]` parameter is optional in `transfergems [Bot] <TargetBots> <Amounts>`, so with only 2 parameters that command is interpreted as `transfergems <TargetBots> <Amounts>`, and `[Bot]` is implied to be whichever bot you sent this command to (or `DefaultBot` if sending commands through the console). 

In most cases you actually would get an error for a missing amount: `Parsing amountNum failed!`, but I think here your `yy` bot has a numeric name that was able to be interpreted as an amount (0 in this case).

**Comment by Nuklon** [comment]
Yes, that's right, my yy bot is named 00 🙃 I guess this is by design then.
