### ISSUE TITLE
Is it possible to add the ability to convert community items into gems?

### ISSUE THREAD

**Issue by d1ret** [Citrinate/BoosterManager#24]
maybe, add command: !cgems (convert gems) C,F (Cards, Foil Cards) ASF (or botname)?
or is it impossible?

**Comment by Citrinate** [comment]
It would be possible, but I don't intend to implement this feature.  I consider this to be the sort of thing that a browser tool with a graphical interface, like [Steam-Economy-Enhancer](https://github.com/Nuklon/Steam-Economy-Enhancer), is much more effective at handling.
