### ISSUE TITLE
Minor suggestion to add a few aliases

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/BoosterManager#3]
There are a few [aliases in ASF](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Commands):

Command | Alias
--- | ---
`addlicense` | `addlicence`
`owns ASF` | `oa`
`status ASF` | `sa`
`redeem` | `r`
`redeem^` | `r^`

---

Similarly, there are a few [aliases in ASFEnhance](https://github.com/chr233/ASFEnhance/blob/master/README.en.md#alias-of-asfs-commands):

| Shorthand              | Equivalent Command             | Description                    |
| ---------------------- | ------------------------------ | ------------------------------ |
| `AL [Bots] <Licenses>` | `ADDLICENSE [Bots] <Licenses>` | Add free `SUB`                 |
| `LA`                   | `LEVEL ASF`                    | Get All bot's level            |
| `BA`                   | `BALANCE ASF`                  | Get All bot's wallet balance   |
| `PA`                   | `POINTS ASF`                   | Get All bot's points balance   |
| `P [Bots]`             | `POINTS`                       | Get bot's points balance       |
| `CA`                   | `CART ASF`                     | Get All bot's cart information |

---

I believe the following aliases could be useful for BoosterManager, and would not cause conflicts with the aforementioned aliases.

Command | Alias
--- | ---
`bstatus ASF` | `bsa`
`gems ASF` | `ga`
`keys ASF` | `ka`

I don't know about the third, but I would use the first two.

**Comment by Citrinate** [comment]
I've added `bsa`, `ga`, and `ka` aliases, as well as a few more for other commands I frequently use with `ASF` attached to them.  They're all documented in the README.  The build I posted [over here](https://github.com/Citrinate/BoosterManager/issues/4#issuecomment-1347361242) has these additions.

**Comment by woctezuma** [comment]
Thank you!
