### ISSUE TITLE
Show AM/PM after the 12-hour times or show the 24-hour times

### ISSUE THREAD

**Issue by woctezuma** [Citrinate/BoosterManager#4]
Information about AM/PM is missing from the output of `bstatus`, e.g.

```
Next booster will be crafted at 4:58 : Duke Nukem 3D: Megaton Edition (225140)
```

However, I believe you must make use of this piece of information to manage the creation of booster packs.

For reference, this is how the information appears on [the official boostercreator page](https://steamcommunity.com/tradingcards/boostercreator/):

```json
{
  "appid": 225140,
  "name": "Duke Nukem 3D: Megaton Edition",
  "series": 1,
  "price": "1000",
  "unavailable": true,
  "available_at_time": "12 Dec @ 4:57pm"
}
```

I would suggest:
- either to show AM/PM after the 12-hour times,
- or to  show the 24-hour times.

This would lead to:

```
Next booster will be crafted at 4:58 PM : Duke Nukem 3D: Megaton Edition (225140)
```

or 

```
Next booster will be crafted at 16:58 : Duke Nukem 3D: Megaton Edition (225140)
```

**Comment by Citrinate** [comment]
It should now 12 or 24-hour times depending on region.  Here's a test build: [BoosterManager.zip](https://github.com/Citrinate/BoosterManager/files/10212181/BoosterManager.zip)

**Comment by woctezuma** [comment]
Thank you!
